{
  imports = [
    ./arr.nix
    ./autoupgrade.nix
    ./blocky.nix
    ./borg.nix
    ./cross-seed.nix
    ./dns.nix
    ./earthwalker.nix
    ./firefox-sync.nix
    ./flatpak.nix
    ./headscale.nix
    ./homeassistant.nix
    ./jellyfin.nix
    ./krb
    ./mailserver.nix
    ./monero.nix
    ./mosh.nix
    ./mullvad.nix
    ./navidrome.nix
    ./printing.nix
    ./ratbag.nix
    ./ssh.nix
    ./syncthing.nix
    ./radicale.nix
    ./resolved.nix
    ./tailscale.nix
    ./transmission.nix
    ./tubearchivist.nix
    ./vaultwarden.nix
    ./webdav.nix
  ];
}
