{
  imports = [
    ./arr.nix
    ./autoupgrade.nix
    ./borg.nix
    ./dns.nix
    ./headscale.nix
    ./homeassistant.nix
    ./jellyfin.nix
    ./mailserver.nix
    ./monero.nix
    ./mosh.nix
    ./navidrome.nix
    ./ssh.nix
    ./syncthing.nix
    ./radicale.nix
    ./resolved.nix
    ./tailscale.nix
    ./transmission.nix
    ./tubearchivist.nix
    ./vaultwarden.nix
    ./webdav.nix
    ./website.nix
  ];
}
