{
  imports = [
    ./arr.nix
    ./autoupgrade.nix
    ./borg.nix
    ./dns.nix
    ./headscale.nix
    ./jellyfin.nix
    ./monero.nix
    ./mosh.nix
    ./mpd.nix
    ./ssh.nix
    ./syncthing.nix
    ./resolved.nix
    ./tailscale.nix
    ./transmission.nix
    ./website.nix
  ];
}
